version: "3.7"

services:
   payment-api:
    container_name: payment.api
    build: ./Services/Payment
    environment:
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - 5000:5000
    depends_on:
      - es01
  
   es01:
    container_name: es01
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - /media/foxbat/a55bb145-7d8e-4eb7-88a8-aab4a16e1cf9/Docker_volumes/elastic/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    mem_limit: 1g
